import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})

export class Member {
  id: number;
  name: string;
  jpg: string;
  bio: string;
}

export class DataService {

  currentMember = 1;
  members: Member[] = [
    {id:1, name:"Noha Ahmed", jpg:"assets/team/Noha.jpg", bio:'Hello my name is Noha Ahmed, team Manager for Team Sudan, I’m a final year Biomedical engineering student. Skilled in programming, content writing and team management. Also I have an intermediate level in German language. Also I have a 3 years volunteering experience, I was an active volunteer at IEEE SUSTech SB, I was a Vice-Chairperson then I was the Chairperson, we served engineering students through our sessions, events and courses related to engineering and technology in overall. Also I volunteered at PROTON SOLAR RACING TEAM in digital marketing, and I learn a lot from team members and managers. As I said before in the Team’s video “I think youth are smart enough to solve global problems if they have the proper mentorship and support”, that’s why I participated with Team Sudan, beside our youth deserves opportunities to show their potentials. In my opinion Team Sudan – FIRST Global is just an example of youth power, and we are hopeful for a better future. '},
    {id:2, name:"Ahmed Abdelwadod", jpg:"assets/team/Ahmed.jpg", bio:"I'm Ahmed Abdelwadod, mentor of Team Sudan. I'm a software developer with 7 years of experience. I've working in several open-source and commercial projects that involved technologies of embedded systems, robotics and IoT applications. In FGC 2017 I was a member in Team Sudan, and today I'll be mentoring the team. Teaching youth about STEM and robotics is what we need to develop our country, we need to solve problems more faster and smarter, and that's what robots do! Getting youth into this industry is a gateway to the future, and I dream that one day each student in Sudan will know how to make a robot."},
    {id:3, name:"Omer Hayder", jpg:"assets/team/Omer.jpg", bio:"Hi, I am Omar Hayder, I’m 17 years old and I’m high school graduate student from Abdullah El-Tayeb School for gifted students, I am going to study electrical engineering in University of Khartoum. My biggest dream is to become an effective and helpful person for my society and my nation. Since childhood I have been interested in assembling parts together and make new things. I discovered that I love electronics, mathematics, computer, engineering, AI and generally technology. In other words, I have passion in MECHATRONICS and STEM. I have good experience in these field, I have already made my own projects and take part in many events and competitions and gain certificates and prizes I also like debates and critical thinking (as a result of loving algorithms). I also participated in debate's competition and my team won it. I want to develop myself on these fields to become able to develop my nation, I think FIRST GLOBAL CHALLENGE is a great opportunity to gain more knowledge and experience, also to know different people with their different cultures furthermore I will practice the togetherness."},
    {id:4, name:"sara Almusbah", jpg:"assets/team/Sara.jpg", bio:" I am Sara Almusbah. I am a high school graduate. I studied at the gifted and talented schools where we learned about robotics since the 4th grade. I’m interested in the robotics field and I love learning about it. I also love books and designing. I joined this challenge because I want to increase my knowledge about robotics and to open the door for new cultures also it's a different experience. I think that FIRST Global Challenge will be the turning point for my life if I have the proper passion and power to do it. I want to thank FIRST Global for this opportunity.  We are learning a lot and having fun. Thank you!    "},
    {id:5, name:"Dania Rida", jpg:"assets/team/Dania.jpg", bio:"Hello, I am Dania Rida, I am a high school graduate student from Abdullah El-Tayeb School for gifted students, with big dreams and great ambitious! Since childhood I’ve been interested in engineering and the mechanism of everything around me, and how the world can be such an interesting place and I carried my curiosity along with me. I am really interested in Mechatronics, AI and robotics, and everything related to technology. Also interested in arts, designing, graphics, Photoshop, video and pictures edits. Nature, cultures and languages, critical thinking and debates took a big part of my attention and I have a good amount of experience in all of them, I've been into a lot of events and exhibitions, did more than a project and joined a great number of local contests and ended up with great results and high ranks. My greatest dream is to obtain knowledge and be able to use it to cure the world, inspire people in my community and be able to make positive changes for humanity. I am constantly in a challenge with myself, and First Global is a golden opportunity to gain knowledge and expertise, and to create a great social network and learn about worldwide cultures."},
    {id:6, name:"Momen Abdelwadoud", jpg:"assets/team/Momen.jpg", bio:' My name is Momen, I studied in gifted and talented schools and graduated from about 5 months ago. I’m so interested in STEM fields more than anything else, I love to learn more and more about technology every day, I want to be an applications developer in the future and have some good companies in my job. I participated in First Global Challenge because I think this may be a perfect beginning in my life career from the age of 17, also I want to meet other interested students from other nationalities and gain their experiences through this event.'},
    {id:7, name:"Elaf Shamseldin", jpg:"assets/team/Elaf.jpg", bio:'Hi, l am Elaf Shams Eldin. I am a high school graduate student from gifted and talented children school.I am interested in robotics and innovation, almost everything new and specialized in Science, technology, Engineering and mechatronics (STEM).     I have a good experience in all STEM fields and I already made my own projects and contributed in many exhibitions and contests. I also love books and writing specially short stories and novels. All these things made me interested in creating a new personality for myself and making it special and start to build my career for this I needed an excellent start and I found it in First Global Challenge.'}
  ]
  constructor() { }

  getCurrentMember(): Member{
    return this.members[this.currentMember-1];
  }
}
